# Generated by Django 4.1.3 on 2022-11-03 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uavs", "0002_uavcompany_uav_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="UavBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uav_brand_company",
                        to="uavs.uavcompany",
                    ),
                ),
            ],
        ),
    ]
