# Generated by Django 4.1.3 on 2022-11-05 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uavs", "0006_rename_genre_uav_name_remove_uav_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uav",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brand",
                to="uavs.uavbrand",
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="category",
                to="uavs.uavcategory",
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company",
                to="uavs.uavcompany",
            ),
        ),
        migrations.AlterField(
            model_name="uav",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
