# Generated by Django 4.1.3 on 2022-11-03 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uavs", "0003_uavbrand"),
    ]

    operations = [
        migrations.AddField(
            model_name="uav",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uav_brand",
                to="uavs.uavbrand",
            ),
        ),
    ]
