# Generated by Django 4.1.3 on 2022-11-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uavs", "0005_uavcategory_uav_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uav",
            old_name="genre",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="uav",
            name="title",
        ),
    ]
